app_key: "mmt4gmgvzlxp3om"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "n8SijtcOZLwAAAAAAAAASFsagCW4BAY8QeAgBoLu50jXgNOgthTmtDs8k5jjasxX"
access_token_secret: <%= ENV["APP_TOKEN_SECRET"] %>
user_id: "312517640"
access_type: "app_folder"